### ISSUE TITLE
Cannot Upload CO Emission To Database

### ISSUE THREAD

**Issue by DerekRuiz** [DerekRuiz/SumoLachineArea#12]
When creating the CO Emission table, the sql query detects the column is already created, and aborts the completion of the CO emission table. This should not occur since the table is newly created and no columns exist except for "osm_id". This does not occur for any of the other emissions.

Image of the CO Emission table after execution: 
![image](https://user-images.githubusercontent.com/47483376/94318502-b5c3cd80-ff56-11ea-8507-43cb0a0d2402.png)

Traceback (most recent call last):
  File "c:/Users/epicb/Documents/GitHub/SumoLachineArea/test.py", line 10, in <module>
    g.saveDataFrame(0,3600,900,['fuel','co','co2','hc','pmx','nox'])
  File "c:\Users\epicb\Documents\GitHub\SumoLachineArea\sumoplustools\emissions\generateEmissions.py", line 129, in saveDataFrame
    self.sqlConnection.saveDataFrame(dataFrame, eType, overide=True)
  File "c:\Users\epicb\Documents\GitHub\SumoLachineArea\sumoplustools\postgresql\psqlObjects.py", line 68, in saveDataFrame
    self.execute('ALTER TABLE public."%s" ADD "%s" numeric;' % (table, cols))
  File "c:\Users\epicb\Documents\GitHub\SumoLachineArea\sumoplustools\postgresql\psqlObjects.py", line 16, in execute
    self.cursor.execute(query)
psycopg2.errors.DuplicateColumn: column "0:00:0.00-0:15:0.00" of relation "CO Emissions" already exists

**Comment by DerekRuiz** [comment]
Issue is resolved with the newest patch.
